# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:55
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Content'},
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', cms.blocks.HeadingBlock()), ('rich_text', cms.blocks.RichTextBlock()), ('image', cms.blocks.ImageBlock()), ('embed', cms.blocks.EmbedBlock())), blank=True),
        ),
    ]
