# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=inventory.models.image_path, verbose_name='image 2'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, upload_to=inventory.models.image_path, verbose_name='image 3'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_4',
            field=models.ImageField(blank=True, upload_to=inventory.models.image_path, verbose_name='image 4'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_5',
            field=models.ImageField(blank=True, upload_to=inventory.models.image_path, verbose_name='image 5'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.TextField(blank=True, verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=inventory.models.image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.TextField(blank=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
