# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160806_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.URLField(blank=True, verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.URLField(blank=True, verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.URLField(blank=True, verbose_name='image 4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.URLField(blank=True, verbose_name='image 5'),
        ),
    ]
