# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160806_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=500, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.URLField(blank=True, max_length=500, verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.URLField(blank=True, max_length=500, verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.URLField(blank=True, max_length=500, verbose_name='image 4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.URLField(blank=True, max_length=500, verbose_name='image 5'),
        ),
    ]
