# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160807_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='link'),
        ),
    ]
