# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_1',
            field=models.URLField(blank=True, max_length=1000, verbose_name='image 1'),
        ),
    ]
