# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20160807_0019'),
    ]

    def create_initial(apps, schema_editor):
        Quality = apps.get_model('inventory', 'Quality')
        Quality.objects.create(name='good')

    def delete_initial(apps, schema_editor):
        MediaType = apps.get_model('inventory', 'Quality')
        MediaType.objects.filter(name='good').delete()

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'quality',
                'verbose_name_plural': 'qualities',
            },
        ),
        migrations.RunPython(create_initial, delete_initial),
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.Quality', verbose_name='quality'),
            preserve_default=False,
        ),
    ]
