# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160808_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price minimum'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='shipping costs'),
        ),
    ]
