# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20160808_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='platforms',
            field=models.ManyToManyField(to='inventory.Platform', verbose_name='platforms'),
        ),
    ]
