# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20160818_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='platforms',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
