# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 13:04
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('inventory', '0011_auto_20160818_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.wagtailcore.fields.StreamField((('heading', cms.blocks.HeadingBlock()), ('rich_text', cms.blocks.RichTextBlock()), ('image', cms.blocks.ImageBlock()), ('embed', cms.blocks.EmbedBlock())), blank=True)),
            ],
            options={
                'verbose_name': 'Inventory',
            },
            bases=('wagtailcore.page',),
        ),
    ]
