# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
